# Generated by Django 6.0.5 on 2026-06-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('researcher', 'Principal Investigator / Researcher'), ('peer_reviewer', 'Academic Peer Reviewer'), ('general_public', 'General Observer')], default='researcher', max_length=20),
        ),
    ]
