# Generated by Django 6.0.5 on 2026-06-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='bio_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='academic_position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
