# Generated by Django 6.0.5 on 2026-06-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_portfolio_bio_text_userprofile_academic_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='google_scholar',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='orcid',
        ),
    ]
